# CONFIG FOR GOOGLE APP ENGINE
runtime: python39

instance_class: F1

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

entrypoint: gunicorn -w 1 -b :$PORT gasmoney:app
